### PR TITLE
Fix https://github.com/mickaelistria/eclipse-bluesky/issues/51

### PR DESCRIPTION
**Pull request by angelozerr**
Recompute width of GlyphMetrics used to takes place when resize of StyledText is done. See
https://github.com/mickaelistria/eclipse-bluesky/issues/51
Signed-off-by: angelozerr <angelo.zerr@gmail.com>

### CODE REVIEW

**Comment by angelozerr** [comment]
@mniewrzal please try this PR too please. I hope it will fix your problem with https://github.com/mickaelistria/eclipse-bluesky/pull/43#issuecomment-329428445

**Comment by mniewrzal** [comment]
> @mniewrzal please try this PR too please. I hope it will fix your problem with #43 (comment)

Looks much better, thanks :)
screenshot from 2017-09-19 10-36-48

**Comment by mickaelistria** [comment]
This patch doesn't fix #51. I see the preview well placed when I resize the editor (the eclipse EditorPart), but resizing the font doesn't necessarily resize the editor, not does it send any kind of SWT event directly. I think the behavior you added could be added directly to the ColorSymbolDrawingStrategy, which should utlimately invoked on all paints (and zooming does trigger a paint).

**Comment by angelozerr** [comment]
> This patch doesn't fix #51. I see the preview well placed when I resize the editor (the eclipse EditorPart), 

It works if you Zomm In/Out, no?

> but resizing the font doesn't necessarily resize the editor, not does it send any kind of SWT event directly. 

You mean that you resize the font with eclipse preferences? How can do that? Is there a common use case?

> I think the behavior you added could be added directly to the ColorSymbolDrawingStrategy, which should utlimately invoked on all paints (and zooming does trigger a paint).

No it will not work. The update of width of GlyphMetrics muts be done BEFORE the paint event (which draws lines). The SWT.REsize is done before the draw of lines, that's why it should work with Zoom In/Out.

**Comment by mickaelistria** [comment]
No, it doesn't work with zoom in/out. It seems like on Linux, changing font size (with Ctrl+/- or other) doesn't send a resize event.

**Comment by angelozerr** [comment]
> No, it doesn't work with zoom in/out. It seems like on Linux, changing font size (with Ctrl+/- or other) doesn't send a resize event.s.

Ok thanks for your feedback. Please retry it. I do the same thing but now when font changes

**Comment by mickaelistria** [comment]
Thanks a lot, this works for me! Anything else to consider before we merge this patch?

**Comment by angelozerr** [comment]
> Thanks a lot, this works for me! 

Cool!

> Anything else to consider before we merge this patch?

I think you can merge it. Perhaps we could improve the condition to recompute the width of GlyphMetrics when font change https://github.com/mickaelistria/eclipse-bluesky/pull/53/files#diff-b8c6375e6ae5b38201372af3df831675R163 like FontPropertyChangeListener of do:

```java
if (getFontPropertyPreferenceKey().equals(property) && !isBlockSelectionModeEnabled()) {
				initializeViewerFont(fSourceViewer);
				updateCaret();
				return;
			}
```

But I think it's not a blocking issue.

**Comment by mickaelistria** [comment]
Reformatted a bit commit message, rebased and merged as e46967d50948ad132acf8b499b751b48beeaed85 . Thanks a lot!

**Pull request closed without merging**
