### PR TITLE
Update commons-compress to 1.26.2

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov 

Unfortunately WWD was bitten by the certificate problem:

image

https://github.com/eclipse-simrel/simrel.build/commit/e4905d9ba5f69c68f6a7399f7de1a961be885569

So I took the liberty to update the target platform.

**Comment by merks** [comment]
The tests fail like this:
```
java.lang.NoClassDefFoundError: org/apache/commons/lang3/SystemProperties
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.normalizeFileName(TarArchiveEntry.java:231)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.setName(TarArchiveEntry.java:1871)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:452)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:389)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:49)
	at org.eclipse.wildwebdeveloper.embedder.node.CompressUtils.extractArchive(CompressUtils.java:71)
...
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.SystemProperties cannot be found by org.apache.commons.commons-compress_1.26.2
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 103 more
```

The class does exist:

image

The bundle org.apache.commons.commons-compress declares an **optional** dependency:

resolution:=optional,org.apache.commons.lang3;

The same was the case for 1.26.1.

But it doesn't appear so optional does it...

**Comment by merks** [comment]
@akurtakov 

Woo hoo, finally the build and tests worked.  🥳

**Comment by akurtakov** [comment]
The npm update is not caused by this update thus I'm merging it.

**Comment by merks** [comment]
I was just thinking that we probably should increment the versions of these three bundles too:

image

So that the new release has new artifacts for these.  Right?

**Comment by merks** [comment]
Yes, I tested the snapshot build and it has these failures problems:

image

**Pull request merged**
