### PR TITLE
Issue #16: Improve condition to avoid NPE

### PR DESCRIPTION
**Pull request by mickaelistria**
Signed-off-by: Mickael Istria <mistria@redhat.com>

### CODE REVIEW

**Comment by mickaelistria** [comment]
@vogella: can you please give it a try?

**Comment by mickaelistria** [comment]
The change was rebased. Can you please give it a new try?

**Comment by vogella** [comment]
Still getting an exception during build... Need to update the other bug report... But super busy at the moment...

**Comment by mickaelistria** [comment]
Rebased and merged as 82b6f1eed297105b29474071cd979b20e3c8e9d4

**Pull request closed without merging**
